### ISSUE TITLE
TypeError: torch.index_select received an invalid combination of arguments - got (torch.cuda.FloatTensor, int, torch.LongTensor), but expected (torch.cuda.FloatTensor source, int dim, torch.cuda.LongTensor index)

### ISSUE THREAD

**Issue by luisfredgs** [clairett/sentiment-classification#1]
i've got this error:

Train epoch 1:   0%|                                                                                                                                                  | 0/1384 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train_batch.py", line 200, in <module>
    avg_loss, acc = train_epoch_progress(model, train_iter, loss_function, optimizer, text_field, label_field, epoch)
  File "train_batch.py", line 64, in train_epoch_progress
    pred = model(sent)
  File "/home/luisfredgs/anaconda3/envs/MachineLearning/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/luisfredgs/Documentos/machine-learning/nlp/pytorch/pytorch-sentiment-classification/lstm.py", line 31, in forward
    x = self.embeddings(sentence).view(len(sentence), self.batch_size, -1)
  File "/home/luisfredgs/anaconda3/envs/MachineLearning/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/luisfredgs/anaconda3/envs/MachineLearning/lib/python3.5/site-packages/torch/nn/modules/sparse.py", line 103, in forward
    self.scale_grad_by_freq, self.sparse
  File "/home/luisfredgs/anaconda3/envs/MachineLearning/lib/python3.5/site-packages/torch/nn/_functions/thnn/sparse.py", line 59, in forward
    output = torch.index_select(weight, 0, indices.view(-1))
TypeError: torch.index_select received an invalid combination of arguments - got (torch.cuda.FloatTensor, int, torch.LongTensor), but expected (torch.cuda.FloatTensor source, int dim, torch.cuda.LongTensor index)

Could you help?

**Comment by NiHaozheng** [comment]
same problem here!

**Comment by clairett** [comment]
Since I don't have access to GPU now, I cannot test if it works but I think the issue can be solved with replacing `model.embeddings.weight.data.copy_(torch.from_numpy(pretrained_embeddings))` with `model.embeddings.weight.data.copy_(torch.from_numpy(pretrained_embeddings).cuda())`

**Comment by NiHaozheng** [comment]
Thanks for your reply. However this solution does not solve the problem. Actually the embedding is already torch.cuda.FloatTensor without coda().  
Btw,I would recommend Google Colab if you need free GPU for testing. It's free and handy. 
[Introduction of Google Colab](https://medium.com/deep-learning-turkey/google-colab-free-gpu-tutorial-e113627b9f5d)

**Comment by clairett** [comment]
@NiHaozheng Did you try `nn.NLLLoss().cuda()`

**Comment by NiHaozheng** [comment]
@clairett I tried just now, didn't work either.

**Comment by clairett** [comment]
@NiHaozheng Currently, I don't have stable internet connection to run the program. By looking at the code, ` train_iter, dev_iter, test_iter = data.BucketIterator.splits((train, dev, test),
                batch_sizes=(batch_size, len(dev), len(test)), sort_key=lambda x: len(x.text), repeat=False, device=-1)` should be changed to `device=None` for GPU.

**Comment by NiHaozheng** [comment]
@clairett Yes it worked!!! Thanks so much. A minor issue is every `pred_label = pred.data.max(1)[1].numpy()` should be change to `pred_label = pred.data.max(1)[1].cpu().numpy()` to transform cuda tensor to numpy.

**Comment by clairett** [comment]
Glad to know, thanks for trying it on GPU.
